### PR TITLE
conda 4.11.0

### PR DESCRIPTION
**Pull request by jezdez**
Changelog: https://docs.conda.io/projects/conda/en/latest/release-notes.html

### CODE REVIEW

**Review by chenghlee — APPROVED** [review]

**Comment by jezdez** [comment]
@chenghlee Just a heads-up I've only now noticed that the version should have been `4.11.0` and not `4.11`. Fixed now!

**Comment by skupr-anaconda** [comment]
License should be BSD-3-Clause and not BSD 3-Clause

**Comment by chenghlee** [comment]
Closing this PR; will wait for conda 4.11.1 to avoid breaking conda build (conda/conda-build#4333).

**Comment by kenodegard** [comment]
Any insight as to why this failed? Does the build need to be reinitiated now that conda-build 3.21.7 is release to defaults?

**Comment by jezdez** [comment]
Let's try and see!

**Comment by jezdez** [comment]
Oh boo, prefect doesn't rebuild on reopen?

**Pull request merged**
