### PR TITLE
Update to 4.13.0.

### PR DESCRIPTION
**Pull request by jezdez**
Release: https://github.com/conda/conda/releases/tag/4.13.0
Docs: https://docs.conda.io/projects/conda/en/latest/release-notes.html#id1

### CODE REVIEW

**Comment by chenghlee** [comment]
Removed upstream test suite from the output package, since we are not running it as part of the package build process anyways. This should dramatically reduce the size of the package and limit false-positives from certain security scanners (e.g., ContinuumIO/anaconda-issues#12937).

**Comment by jezdez** [comment]
@chenghlee I wonder if it would be a good idea to apply the same change as https://github.com/conda-forge/conda-feedstock/commit/500f6327c5465e028fd33aa0845106ba73c4024d since it effectively does the same and it's weird that the recipes diverge so much at the moment.

**Review by cbouss — COMMENTED** [review]
Missing field license_family, otherwise, LGTM

**Comment by chenghlee** [comment]
> @chenghlee I wonder if it would be a good idea to apply the same change as [conda-forge@500f632](https://github.com/conda-forge/conda-feedstock/commit/500f6327c5465e028fd33aa0845106ba73c4024d) since it effectively does the same and it's weird that the recipes diverge so much at the moment.

I started with that c-f changeset but didn't particularly like the variable name. (I preferred a name that described which tests were selected, rather than the testing framework.)

I don't mind changing it to match but also feel that if we are going to do that, we may as well to put the effort into completely aligning the recipes. (I know the test scripts are already quite different.)

**Comment by chenghlee** [comment]
> @chenghlee I wonder if it would be a good idea to apply the same change as [conda-forge@500f632](https://github.com/conda-forge/conda-feedstock/commit/500f6327c5465e028fd33aa0845106ba73c4024d) since it effectively does the same and it's weird that the recipes diverge so much at the moment.

I started with that c-f changeset but didn't particularly like the variable name. (I preferred a name that described which tests were selected, rather than the testing framework.)

I don't mind changing it to match but also feel that if we are going to do that, we may as well to put the effort into completely aligning the recipes. (I know the test scripts are already quite different.)

**Review by ScottBailey — APPROVED** [review]
lgtm

**Pull request merged**
