### PR TITLE
Bump to 23.7.2

### PR DESCRIPTION
**Pull request by kenodegard**
Hotfix correcting --json/--debug for `conda env`

Xref https://github.com/conda/conda/issues/12849

Changelog https://github.com/conda/conda/blob/23.7.2/CHANGELOG.md

### CODE REVIEW

**Review by cbouss — APPROVED** [review]

**Review by ryanskeith — CHANGES_REQUESTED** [review]
Requests dependency doesn't match.
https://github.com/conda/conda/blob/416993b967db33a22b1270bc83e10aa6f71c8bba/pyproject.toml#L33

Otherwise looks good to me.

**Review by ryanskeith — APPROVED** [review]
These look good to me, now.

**Comment by jezdez** [comment]
@ryanskeith The conda dependencies are NOT tracked in pyproject.toml but the conda recipe file in https://github.com/conda/conda/blob/416993b967db33a22b1270bc83e10aa6f71c8bba/recipe/meta.yaml#L46.

This should have been checked and is in fact an inconsistency in conda. I’m not sure what to do now though, this wasn’t needed for the release :-/

@chenghlee Any idea what to do now?

**Comment by kenodegard** [comment]
@jezdez per this PR https://github.com/conda/conda/pull/12683 the recipe in conda is actually incorrect and updating the requests dependency is the correct move

**Comment by jezdez** [comment]
@kenodegard even better, thank you for finding that, I didn't know

**Pull request merged**
