### PR TITLE
conda 23.3.0 release

### PR DESCRIPTION
**Pull request by kenodegard**
Bumping conda version.

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
I've updated the dependencies:
- rebuilt **pyopenssl 23.0.0** missing for **python 3.11**
- packaging to 23.0

**Comment by skupr-anaconda** [comment]
@jezdez Something is wrong with `packaging` and version or conda activation in the build.sh:
```
  File "/Users/builder/miniconda3/envs/prefect/lib/python3.9/site-packages/packaging/version.py", line 195, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
```

**Comment by kenodegard** [comment]
@skupr-anaconda may I get the full stack trace?

**Comment by skupr-anaconda** [comment]
```
INFO:conda_build.source:Downloading https://github.com/conda/conda/archive/23.3.0.tar.gz
Downloading https://github.com/conda/conda/archive/23.3.0.tar.gz
Success

Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)

  File "/opt/conda/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)

  File "/opt/conda/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)

  File "/croot/conda_1678970012846/work/conda/__init__.py", line 10, in <module>
    from .deprecations import deprecated

  File "/croot/conda_1678970012846/work/conda/deprecations.py", line 9, in <module>
    from packaging.version import parse, Version

ModuleNotFoundError: No module named 'packaging'

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

**Comment by skupr-anaconda** [comment]
It fails again with exactly the same error as above mentioned

**Comment by kenodegard** [comment]
@skupr-anaconda can you check which version of conda-build it fails with?

**Comment by skupr-anaconda** [comment]
Prefect still uses the previous version of conda-build:
`Conda version Info: ['conda 23.1.0', 'conda-build 3.23.3', 'conda-package-handling 2.0.2']`

**Comment by skupr-anaconda** [comment]
This issue should be fixed in `run_test.bat` too https://anaconda.atlassian.net/browse/PKG-913

**Comment by jezdez** [comment]
> This issue [anaconda.atlassian.net/browse/PKG-913](https://anaconda.atlassian.net/browse/PKG-913) should be fixed in run_test.bat too

I'm not following, where should this be added? @pseudoyim can you elaborate https://anaconda.atlassian.net/browse/PKG-913?

**Comment by dbast** [comment]
```
Traceback (most recent call last):
15:12:09
INFO
build
  File "/opt/conda/bin/conda-build", line 11, in <module>
15:12:09
INFO
build
    sys.exit(main())
15:12:09
INFO
build
  File "/opt/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 496, in main
15:12:09
INFO
build
    execute(sys.argv[1:])
15:12:09
INFO
build
  File "/opt/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 485, in execute
15:12:09
INFO
build
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
15:12:09
INFO
build
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
15:12:09
INFO
build
    return build_tree(
15:12:09
INFO
build
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3091, in build_tree
15:12:09
INFO
build
    packages_from_this = build(metadata, stats,
15:12:09
INFO
build
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2214, in build
15:12:09
INFO
build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
15:12:09
INFO
build
  File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 412, in check_call_env
15:12:09
INFO
build
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
15:12:09
INFO
build
  File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
15:12:09
INFO
build
    raise subprocess.CalledProcessError(proc.returncode, _args)
```

**Review by jezdez — APPROVED** [review]

**Pull request merged**
