### PR TITLE
Add the upper bound <0.11.3 for toolz & cytoolz

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Actions:
1. Add the upper bound **<0.11.3** for `toolz` & `cytoolz` to prevent undesirable changes and to unblock [PKG-127](https://anaconda.atlassian.net/browse/PKG-127)
2. Add license_url, doc_source_url, update home url

### CODE REVIEW

**Review by varlackc — APPROVED** [review]
LGTM

**Review by ryanskeith — APPROVED** [review]
These look good to me.

**Review by cbouss — COMMENTED** [review]
LGTM but there should be a corresponding repodata hotfix for conda versions <= 22.9.0 b0.

You can try locally but I think installing toolz 0.12 with conda will install conda 22.9.0 b0, and not b1.

**Review by cbouss — CHANGES_REQUESTED** [review]
Digging a bit more: 
- The release note of toolz does not match the actual changes in the source. (diffing the two tarballs gives the same as this tag diff from github: https://github.com/pytoolz/toolz/compare/0.11.2...0.12.0)
- I don't see major changes between toolz 0.11.2 and 0.12.0
- A hotfix on conda would touch a lot of versions

Based on the above, could we just update toolz and not rebuild conda/apply hotfix to conda?

**Pull request closed without merging**
